name: Salesforce Backup
on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: write
  checks: write
  statuses: write

env:
  LOG_LEVEL: "INFO"
  DEBUG: "true"
  POWERTOOL_SERVICE_NAME: "GHAction"
  SalesforceConsumerKey: ${{ secrets.SALESFORCE_CONSUMER_KEY }}
  SalesforceConsumerSecret: ${{ secrets.SALESFORCE_CONSUMER_SECRET }}
  SalesforcePass: ${{ secrets.SALESFORCE_PASSWORD }}
  SalesforceSecurityToken: ${{ secrets.SALESFORCE_SECURITY_TOKEN }}
  SalesforceUser: ${{ secrets.SALESFORCE_USER }}
  SALESFORCE_TIMEOUT_SECONDS: 30
jobs:
  s3-backup:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

    - name: configure aws credentials using OIDC
      uses: aws-actions/configure-aws-credentials@e1e17a757e536f70e52b5a12b2e8d1d1c60e04ef # v2.0.0
      with:
        role-to-assume: arn:aws:iam::563894450011:role/salesforce-backup
        role-session-name: salesforce-backup
        aws-region: ca-central-1

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: install dependencies
      run: make requirements

    - name: pull down file
      run: make run-local

    - name: Create ZIP bundle
      run: |
        ZIP_FILE=`basename ${{ github.repository }}`-`date '+%Y-%m-%d'`.zip
        zip -rq "${ZIP_FILE}" .
        mkdir -p ${{ github.repository }}
        mv "${ZIP_FILE}" ${{ github.repository }}

    - name: Upload to S3 bucket
      run: |
        aws s3 sync ./csv s3://cds-salesforce-backups